frontend/controllers/CartController.php
<?php
namespace frontend\controllers;

use frontend\models\Product;
use Yii;

class CartController extends \yii\web\Controller {

    public function actionIndex() {
        if(Yii::$app->cart->getIsEmpty()){
            return $this->render('emptycart');
        }
        return $this->render('index');
    }

    public function actionUpdateItem($id, $qty) {
        $product = Yii::$app->cart->getPositionById($id);
        Yii::$app->cart->update($product,$qty);
        if(Yii::$app->request->isAjax){
            return ;
        }
        
        return $this->redirect(['index']);
    }

    public function actionAddItem($id, $size=null) {
        $product = Product::find()->andWhere(['id'=>$id])->one();
        $product->sizeId = $size;
        // add an item to the cart
        Yii::$app->cart->put($product);
    }

    public function actionClear() {
        Yii::$app->cart->removeAll();
    }

    public function actionDeleteItem($id) {
        Yii::$app->cart->removeById($id);
        if(Yii::$app->request->isAjax){
            return ;
        }
        $this->redirect(['index']);
    }

}

frontend/views/cart/_cartSummary.php
<?php 
use yii\helpers\Url;
?>
<div class="row " id="total-row">
    <div class="col-md-6 col-sm-6 cart-summry-notnow">
        <a class="btn pull-right" href="<?= Url::to(['/']) ?>"><span><</span><?= Yii::t('cart', 'Continue shopping') ?></a>
    </div>
    <div class="col-md-6 col-sm-6 all-price">
        <div class="row" id="individual-prices">
            <div class="col-md-8 col-sm-8">
                <p><?= Yii::t('cart', 'subtotal')?></p>
            </div>
            <div class="col-md-4 col-sm-4">
                <p><?=Yii::$app->formatter->asCurrency(Yii::$app->cart->cost);?></p>
            </div>
            <div class="col-md-8 col-sm-8">
                <p><?= Yii::t('cart', 'estimated shipping')?>
                <a href="#"><?= Yii::t('cart', 'Viev option')?>s</a>
                </p>
                
            </div>
            <div class="col-md-4 col-sm-4">
                <p>free</p>
            </div>
        </div>
        <div class="row" id ="sum-of-prices">
            <div class="col-md-8 col-sm-8">
                <p><?= Yii::t('cart', 'estimated total')?></p>
            </div>
            <div class="col-md-4 col-sm-4">
                <p><?=Yii::$app->formatter->asCurrency(Yii::$app->cart->cost);?></p>
            </div>
        </div>
        <div class="row buttons-row">
            <div class="col-md-12 col-sm-12 cart-checkout" >
                <a class="btn btn-default" data-pjax="0" href="<?= Url::to(['checkout/order']) ?>"><?= Yii::t('cart', 'Proceed to checkout') ?></a>
            </div>
            <div class="col-md-12 col-sm-12" id="paypal" style="display: none;" >
                <a class="btn btn-default " data-pjax="0" href="#"><?= Yii::t('cart', 'Check out with') ?></a>
            </div>
        </div>
    </div>



</div>

frontend/views/cart/_yourFavorites.php
<div class="col-md-3 col-sm-3 item-favorites">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <img src="/images/placeholder.gif">
        </div>
        <div class="col-md-12 col-sm-12">
            <p class="cart-item-name">tularosa</p>
            <p class="cart-item-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <p class="cart-item-price">$168.00</p>
            
        </div>
        <div class="col-md-12 col-sm-12">
                <a class="btn btn-default" data-pjax="0" href="#"><?= Yii::t('cart', 'move to bag') ?></a>
        </div>
        <div class="col-md-12 col-sm-12" id="remove-link">
                <a class="" href="#"><?= Yii::t('cart', 'Remove') ?></a>
        </div>
    </div>
</div>


frontend/views/cart/emptycart.php
<?php
use yii\bootstrap\Alert;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
?>

<div class="title-card row">
<h1><?=Yii::t('cart','shopping bag is empty')?></h1>
</div>
<div class="row" style="
    max-width: 1440px;
    margin-left: auto !important;
    margin-right: auto !important;
    padding: 170px 0;
    background: #fff;
    text-align: center;
">
  &lt;<a id="empty-cart-link" class="btn" href="<?=Url::to(['/'])?>" style="
    font-size: 14px;
    color: #4a4a4a;
    font-weight: 600;
    text-transform: uppercase;
"><?=Yii::t('cart', 'Continue shopping')?></a>
</div>

frontend/views/cart/index.php
<?php
/* @var $this yii\web\View */
use frontend\widgets\CartGrid;
use yii\widgets\Pjax;

$removeItemUrl = Yii::$app->urlManager->createUrl(['cart/delete-item']);
$updateItemUrl = Yii::$app->urlManager->createUrl(['cart/update-item']);

$this->title = Yii::t('cart', 'shopping bag');
$this->registerCssFile('/css/cart.css');
$js = <<<JS
        $(document).ready(function(){            
            $('a.cart-item-delete').on('click',function(e){
                e.preventDefault();
                removeCartItem($(this).data('id'));
            });
            
        });
        function refreshCart(){
            $.pjax({container: '#cart'});
        }
        function removeCartItem(itemId){{
            $.get( "$removeItemUrl", { id: itemId}).done(function( data ){
                        refreshCart(); 
                    });
            };
        };
        function changeItemCount(itemId, iqty){{
            $.get( "$updateItemUrl", { id: itemId, qty: iqty}).done(function( data ){
                        refreshCart(); 
                    });
            };
        };
JS;
$this->registerJs($js, \yii\web\View::POS_END);
?>
<div class="title-card row">
<h1><?=$this->title?></h1>
</div>
<?php Pjax::begin(['id'=>'cart']);?>
<div class="row cart-item-title">
    <div class="col-md-2 col-sm-2 cart-item-image">
        <p>item</p>
    </div>
    <div class="col-md-10 col-sm-10 cart-item-properties">
        <div class="row">
            <div class="col-md-4 col-sm-4 cart-item-name">
                <p>description</p>
            </div>
            <div class="col-md-2 col-sm-2 cart-item-color">
                <p>color</p>
            </div>
            <div class="col-md-1 col-sm-1 cart-item-size">
                <p>size</p>
            </div>
            <div class="col-md-1 col-sm-1 cart-item-qty">
                <p>qty</p>
            </div>
            <div class="col-md-2 col-sm-2 cart-item-actions">
               <p>actions</p>
            </div>
            <div class="col-md-2 col-sm-2 ">
              <p>price</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <?=CartGrid::widget([]);?>
    </div>
    <div class="col-md-12 col-sm-12">
        <?=$this->render('_cartSummary');?>
    </div>
</div>
<div class="row" style="display: none"  id="favorires-row">
    <div class="col-md-12 col-sm-12">
    <h1><?= Yii::t('cart', 'your favorites') ?></h1>
    </div>
    <?=$this->render('_yourFavorites');?>
</div>
<?php Pjax::end();?>